-- AlterTable NotificationType (MySQL: alter enum)
ALTER TABLE `Notification` MODIFY `type` ENUM(
  'PROJECT_ACCESS_GRANTED',
  'PROJECT_COLLABORATOR_ACTIVITY',
  'FOLLOW_UP_ANSWERED',
  'FORM_COLLABORATION_INVITE',
  'FORM_COLLABORATION_RESPONSE_SUBMITTED',
  'STRATEGY_PLAN_ACCESS_GRANTED',
  'STRATEGY_PLAN_COLLABORATOR_ACTIVITY',
  'PROJECT_PLAN_ACCESS_GRANTED',
  'PROJECT_PLAN_COLLABORATOR_ACTIVITY'
) NOT NULL;
