-- AlterTable
ALTER TABLE `strategyairun` MODIFY `state` ENUM('STRATEGY_TRANSLATION', 'MAP_GENERATION', 'MAP_VALIDATION', 'KPI_GENERATION', 'KPI_VALIDATION', 'TABLE_GENERATION', 'TABLE_VALIDATION', 'READY_FOR_MONITORING', 'MONITORING', 'FAILED') NOT NULL;

-- AlterTable
ALTER TABLE `strategyplan` MODIFY `state` ENUM('STRATEGY_TRANSLATION', 'MAP_GENERATION', 'MAP_VALIDATION', 'KPI_GENERATION', 'KPI_VALIDATION', 'TABLE_GENERATION', 'TABLE_VALIDATION', 'READY_FOR_MONITORING', 'MONITORING', 'FAILED') NOT NULL DEFAULT 'MAP_GENERATION';
