-- AlterTable
ALTER TABLE `project` MODIFY `status` ENUM('WAITING_FOR_FORM', 'ANALYSIS_PENDING', 'AI_PROCESSING', 'REVIEWING', 'CHAT_MODE', 'FINAL_ANALYSIS', 'FAILED') NOT NULL DEFAULT 'WAITING_FOR_FORM';
